# Generated by Django 3.2 on 2022-10-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'file audio'), (2, 'file video'), (3, 'file pdf')], default=2, verbose_name='file_type'),
            preserve_default=False,
        ),
    ]
